//node('lnxs0755(WMB)') {
node('master') {
   	echo pwd()
	setEnv()
    echo "env.PATH:  ${env.PATH}"
     sh 'env'
    //def mvnHome = '/app/easier/tools/apache-maven-3.3.9'
	echo sh(script: "python --version", returnStdout: true)
	echo sh(script: "ansible --version", returnStdout: true)
	echo sh(script: "java -version", returnStdout: true)
	echo sh(script: "javac -version", returnStdout: true)
	
	String directory = "/BODSSHARE/UKBQ/DSOUT/StockService/"
	String fileName = "SAPR3toStockAPI"
	String extention = ".csv"
	String filePath = "$directory$fileName$extention"
	String actualFilePath = "$filePath" + "_Actual"
	String expectedFilePath = "$filePath" + "_Expected"

	println("filePath: $filePath")
	String oldLastModZipFileName = null;
			
	try {
		stage('Checkout') {
			git url: 'https://github.com/KITSDwarikaPrasad/stock-ci.git',branch: 'ansiblize'
		}
		stage('Build') {
			
				sh "mvn -B compile"
		}
	//	stage('pre-JUnit') {}
// 	dir('script/shell') {
// 	    	sh(script:"sh invokeBodsJob.sh",returnStdout: true)
// 	}

    // dir('/support/home/esradm/myPlaybooks/ansible/psremote') {
    //     sh(script:"sh invokejob.sh", returnStdout: true)
    // }
	
		stage('Test') {
		    echo 'Test starting'
			sh "mvn -B test"
			echo 'Test ending'+{new Date().getTime()}
		}
	} 
	catch (error) {
		stage('Cleanup after fail') {
		    // emailext attachLog: true, body: "Build failed (see ${env.BUILD_URL}): ${error}", subject: "[JENKINS] ${env.JOB_NAME} failed", to: 'dwarika.prasad@kingfisher.com'
			echo error.getMessage()
		    throw error
		}
	}
	finally {

		step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reports/TEST-*.xml'])

		stage('post-JUnit') {
		    //stdout = sh(script: 'sh script/post-run.sh', returnStdout: true)
	    //	sh 'rm ~/SAPR3toStockAPI_1000.csv'
// 		//	sh 'rm ~/SAPR3toStockAPI_1010.csv'
 		    //echo "Deleting the new csv file : $filePath"
 		    //sh 'rm $filePath'
 		    echo "rename the original file back i.e.  SAPR3toStockAPI.csv_bkp --> SAPR3toStockAPI.csv"
 	        sh "mv $filePath" + "_bkp" + " $filePath"
// 			echo "remove other temp files"
// 		//	sh 'rm $expectedFilePath'
// 		//	sh 'rm $actualFilePath'
// 			sh "rm $directory"+ "Unprocessed_log_lhs.txt"
// 			sh "rm $directory"+ "Unprocessed_log_rhs.txt"
			
		}
	}
	
}


def setEnv() {
  env.PATH = 
"/app/easier/tools/apache-maven-3.3.9/bin:/support/home/esradm/usr/local/bin:/support/home/esradm/jdk1.8.0_111/bin:${env.PATH}"
}